export enum AUTH_ACTIONS {
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    SET_TOKEN = 'SET_TOKEN',
    SET_USER = 'SET_TOUSER',
    SET_LOADING = 'SET_LOADING',
    SET_ASSETS_LOADING = 'SET_ASSETS_LOADING',
}